#!/usr/bin/env node
// scripts/redos-scan.mjs
//
// Walks every rule's defaultOptions.pattern (and similar regex-bearing
// fields) and runs them through `safe-regex2` to catch catastrophic
// backtracking patterns before they ship.
//
// Implementation: TODO. Generated by the bootstrap-ci skill as a stub.
// safe-regex2 is in package.json deps but not yet wired (CLAUDE.md
// principle 4 marks it `pending`).

console.log('[redos] TODO: implement ReDoS scan.');
console.log('[redos] Skipping — exit 0 so CI does not break.');
process.exit(0);
